name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e lint

  test:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python: 2.7
            toxenv: py27
          - python: 3.5
            toxenv: py35
          - python: 3.6
            toxenv: py36
          - python: 3.7
            toxenv: py37
          - python: 3.8
            toxenv: py38
          - python: 3.9
            toxenv: py39
          - python: pypy2
            toxenv: pypy2
          - python: pypy3
            toxenv: pypy3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: .coverage

  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: codecov/codecov-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e pywin
