name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e lint

  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy3"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: .coverage

  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: codecov/codecov-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e py
